---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - "SKIP-CHANGELOG"
      - "DEPENDENCIES"
    reviewers:
      - djelinek
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    reviewers:
      - djelinek
  - package-ecosystem: 'npm'
    directory: '/test/utils-test-project'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    reviewers:
      - djelinek
