name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    env:
      CODE_VERSION: max
      TEST_RESOURCES: test-res

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Tests (macOS, windows)
        if: matrix.os != 'ubuntu-latest'
        run: |
          npm test

      - name: Tests (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm test

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots-${{ matrix.os }}
          path: ${{ github.workspace }}/test/**/screenshots/*.png

  check:
    if: always()
    runs-on: ubuntu-latest
    name: Status Check
    needs: [ main ]
    steps:
      - name: Print Test Result
        run: |
          echo result = ${{ needs.main.result }}
      - name: Status Check - success
        if: ${{ needs.main.result == 'success' }}
        run: |
          echo "All tests successfully completed!"
          exit 0
      - name: Status Check - failure
        if: ${{ needs.main.result != 'success' }}
        run: |
          echo "Status Check failed!"
          exit 1
